version: '3'

networks:
    xarxa_gp1f4a11:
        driver: bridge

services:
  gp1asix2:
    build: .
    expose:
      - "80"
    environment:
      - HOST_NAME=desenvolupadorgrup06.fjeclot.net
    ports:
      -
  lb:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gp1asix2
    ports:
      - "80:8000"
    networks:
        - xarxa_gp1f4a11

